# service
apiVersion: v1
kind: Service
metadata:
  name: sms-service
  labels:
    app: sms-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: sms-service

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sms-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sms-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
