# deployment
apiVersion: apps/v2
kind: Deployment
metadata:
  name: sms-service
spec:
  progressDeadlineSeconds: 100
  replicas: 2
  selector:
    matchLabels:
      app: sms-service
  template:
    metadata:
      labels:
        app: sms-service
        version: v2
    spec:
      containers:
        - image: ajoop/sms-service:v2
          imagePullPolicy: Always
          name: sms-service
          ports:
            - containerPort: 8081
